# Generated by Django 5.1.2 on 2024-11-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_precio_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=10),
        ),
    ]
